name: 'Store Playwright Results'
description: 'Store Playwright Results'
inputs:
  githubToken:
    description: 'GitHub Token'
    required: true
  prNumber:
    description: 'Pull request ID (optional)'
    required: false
  conclusion:
    description: 'Conclusion of the previous step'
    required: true
  provider:
    description: 'Deployment Provider'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      if: always()
      with:
        github-token: ${{ inputs.githubToken }}
        script: |
          const conclusion = '${{ inputs.conclusion }}';
          const prNumber = '${{ inputs.prNumber }}';
          const provider = '${{ inputs.provider }}';

          if (prNumber && conclusion) {
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const runId = context.runId;
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              repo,
              owner,
              run_id: runId,
            });
          
            console.log(artifacts);

            const pullRequest = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });
          
            // Create a comment with the artifact links on the pull request
            const artifactLinks = [
              `| Name |  |`,
              `|--------|----------|`,
              `| Provider | ${provider}  |`,
              `| Result | ${conclusion === 'success' ? ':green_circle:' : ':red_circle:'}  |`,
              `| Summary | [Execution Summary](https://github.com/${owner}/${repo}/actions/runs/${runId}/) |`,
            ];
            const comment = artifactLinks.join('\n');
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pullRequest.data.number,
              body: comment
            });
          }
