import './globals.css';
import Footer from './components/Layout/Footer';
import Header from './components/Layout/Header';
import { ClientProvider } from './components/Provider/ClientProvider';
import { SidebarUI } from './components/Sidebar/SidebarUI';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Wix Events Site</title>
        <meta
          name="description"
          content="Generated by create next app with Wix Events integration"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="text-black bg-site">
        <ClientProvider>
          <Header />
          <main className="bg-site min-h-[600px]">{children}</main>
          <SidebarUI />
        </ClientProvider>
        <div className="mt-10 sm:mt-20">
          <Footer />
        </div>
      </body>
    </html>
  );
}
