name: Run E2E Manually for a given URL
# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      deploymentUrl:
        description: 'The deployment URL to test with'
        required: true
      provider:
        description: 'The provider of the URL, used in order to determine the screenshots folder'
        required: true
        default: 'netlify'
jobs:
  manual-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - uses: ./.github/actions/setup-playwright
      - uses: ./.github/actions/run-playwright
        with:
          provider: github.event.inputs.provider
          provider-deployment-url: ${{ github.event.inputs.deploymentUrl }}
